# Generated by Django 4.2 on 2023-05-01 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_comment="slug", max_length=100, verbose_name="slug")),
                ("title", models.CharField(db_comment="title", max_length=255, verbose_name="title")),
                ("start_date", models.DateTimeField(db_comment="start date", verbose_name="start date")),
                ("end_date", models.DateTimeField(db_comment="end date", verbose_name="end date")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="created at", verbose_name="created at"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, db_comment="updated at", verbose_name="updated at")),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_comment="last user who updated",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "form",
                "verbose_name_plural": "forms",
                "db_table": "form",
            },
        ),
        migrations.CreateModel(
            name="Submit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("form_title", models.CharField(db_comment="title", max_length=255, verbose_name="form title")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="created at", verbose_name="created at"),
                ),
                (
                    "form",
                    models.ForeignKey(
                        db_comment="form FK", on_delete=django.db.models.deletion.CASCADE, to="forms.form"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="user who submitted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "submit",
                "verbose_name_plural": "submits",
                "db_table": "submit",
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (100, "TITLE"),
                            (200, "TEXT"),
                            (201, "TEXTAREA"),
                            (300, "RADIO"),
                            (301, "CHECKBOX"),
                            (302, "SELECT"),
                        ],
                        db_comment="type",
                        verbose_name="type",
                    ),
                ),
                (
                    "max_allowed_size",
                    models.SmallIntegerField(
                        blank=True, db_comment="max allowed size", null=True, verbose_name="max allowed size"
                    ),
                ),
                ("title", models.CharField(blank=True, db_comment="title", max_length=255, verbose_name="title")),
                (
                    "description",
                    models.CharField(blank=True, db_comment="description", max_length=500, verbose_name="description"),
                ),
                (
                    "is_required",
                    models.BooleanField(db_comment="is required", default=False, verbose_name="is required"),
                ),
                ("order", models.SmallIntegerField(db_comment="order", default=0, verbose_name="order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="created at", verbose_name="created at"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, db_comment="updated at", verbose_name="updated at")),
                (
                    "form",
                    models.ForeignKey(
                        db_comment="form FK", on_delete=django.db.models.deletion.CASCADE, to="forms.form"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_comment="last user who updated",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "component",
                "verbose_name_plural": "components",
                "db_table": "component",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(db_comment="title", max_length=255, verbose_name="text")),
                ("order", models.SmallIntegerField(db_comment="order", default=0, verbose_name="order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="created at", verbose_name="created at"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, db_comment="updated at", verbose_name="updated at")),
                (
                    "component",
                    models.ForeignKey(
                        db_comment="question FK", on_delete=django.db.models.deletion.CASCADE, to="forms.component"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_comment="last user who updated",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "choice",
                "verbose_name_plural": "choices",
                "db_table": "choice",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "question_title",
                    models.CharField(
                        blank=True, db_comment="component title", max_length=255, verbose_name="question title"
                    ),
                ),
                ("answer", models.CharField(blank=True, db_comment="text", max_length=1000, verbose_name="answer")),
                (
                    "choice_text",
                    models.CharField(blank=True, db_comment="choice text", max_length=255, verbose_name="choice text"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="created at", verbose_name="created at"),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        blank=True,
                        db_comment="choice FK",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="forms.choice",
                        verbose_name="choice",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        db_comment="component FK",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="forms.component",
                        verbose_name="component",
                    ),
                ),
                (
                    "submit",
                    models.ForeignKey(
                        db_comment="submit FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forms.submit",
                        verbose_name="submit",
                    ),
                ),
            ],
            options={
                "verbose_name": "answer",
                "verbose_name_plural": "answers",
                "db_table": "answer",
            },
        ),
    ]
